### PR TITLE
fix: move `microbundle` to dev deps

### LINKED ISSUE #57: `microbundle` should be a dev dependency
#56 made nice refactoring, but has one big bug.
The `microbundle` dependency should be in `devbDependencies`

### PR DESCRIPTION
**Pull request by viceice**
- fixes #57

### CODE REVIEW

**Review by curran — APPROVED** [review]
LGTM, thank you!

**Comment by curran** [comment]
Published as https://github.com/datavis-tech/graph-data-structure/releases/tag/v3.1.0

**Comment by viceice** [comment]
Thank you for fast merge and publish 🎉

**Comment by curran** [comment]
My pleasure! Thank YOU for the contribution!

**Pull request merged**
