### PR TITLE
Wrap up details for new major version release

### LINKED ISSUE #84: Broken tsc
The current state of the `npm run tsc` script fails on type checks. Let's nail all those then cut a major release!

Is this something you might be able to look into @JesusTheHun ? Thanks!

### PR DESCRIPTION
**Pull request by JesusTheHun**
Closes #84 

I added myself as a contributor and updated the signature of the `addEdge` function.

### CODE REVIEW

**Comment by JesusTheHun** [comment]
@curran I've not been able to reproduce the errors of the CI, even using act. This is quite weird.

**Comment by curran** [comment]
Oh, you'll need to pull from the latest `main`. It looks like this PR is a continuation from your previous branch, which has the old command names `lint` and `type-check`. I upgraded dependencies as well, which may be related.

```
<<<<<<< new-major-wrap-up
    "lint": "prettier --write .",
    "type-check": "tsc --noEmit --noEmitOnError",
=======
    "prettier": "prettier --write .",
    "tsc": "tsc --noEmit",
>>>>>>> master
```

**Comment by curran** [comment]
Thanks again for your collaboration on this! Much appreciated.

**Comment by curran** [comment]
Oh thanks a ton for removing the JS files! Sorry, I made a mess with that. Closes #86

**Comment by JesusTheHun** [comment]
CI passes on my branch : https://github.com/JesusTheHun/graph-data-structure/actions/runs/10477332363

**Comment by curran** [comment]
Fantastic!!!

**Comment by curran** [comment]
Merged woohoo!

**Pull request merged**
