### PR TITLE
Update build process + general updates

### PR DESCRIPTION
**Pull request by TimMikeladze**
- Setup microbundle for the build process. This emits multiple bundle types for esm and cjs,  eliminates the needs for browserify step, and opens up a path for implementing #18 
- Added Github workflow @curran can the travis.yml file in the root be removed?
- Added `prettier` to format the codebase
- Added `release-it` to tag and publish semantic releases to Github / NPM.
- Updated and pinned all packages

### CODE REVIEW

**Comment by curran** [comment]
Wow some very nice work here! Thank you so much. It all looks great to me!

**Comment by curran** [comment]
The one thing I'm not sold on is `release-it`, which adds 200 additional transitive dependencies.

**Comment by curran** [comment]
But hey maybe it's fine. Looks like a popular tool! Will give it a try.

**Comment by TimMikeladze** [comment]
No problem. Thank you for the merge!

**Pull request merged**
